# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"
  ];
  boot.kernelParams = [ "acpi_osi=!" "acpi_osi=\"Windows 2009\"" ];
  boot.kernelModules = [ "kvm-intel" "nvidia" ];
  boot.blacklistedKernelModules = [ "nouveau" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    options kvm_intel nested=1
  '';
  nix.maxJobs = 8;
  nix.buildCores = 8;

  #boot.extraModprobeConfig = ''
  #  options snd-hda-intel single_cmd=1
  #  options snd-hda-intel probe_mask=1
  #  options snd-hda-intel model=generic
  #'';

  nixpkgs.config.pulseaudio = true;
  hardware.pulseaudio.enable = true;
  sound.enable = true;
  hardware.bumblebee =
  { enable = true;
    # pmMethod = "none";
    driver = "nvidia"; };
  hardware.opengl =
  { driSupport32Bit = true;
    extraPackages = [ pkgs.vaapiIntel ]; };
  hardware.cpu.intel.updateMicrocode = true;
}
